apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: swoufo1yo-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:2da2a9ddef1b24cd66c7d099a2b76de74e8076eb@sha256:f145d225bcf0a19dd7425b326fe72a61f56e450b341b0919d26d2d5c68cd7544
          name: container-image
