apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: swoufo1yo-nodejs
  janus-idp.io/tekton: swoufo1yo-nodejs
  backstage.io/kubernetes-id: swoufo1yo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: swoufo1yo-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
