apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: swoufo1yo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: swoufo1yo-nodejs 
  name: swoufo1yo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: swoufo1yo-nodejs 
